apiVersion: v1
kind: Service
metadata:
  name: pointcloudtools-main-service
spec:
  type: LoadBalancer
  selector:
    app: pointcloudtools-main
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 15672